# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_img_pb2 as grpc__img__pb2


class testImageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendImage = channel.unary_unary(
        '/testImage/SendImage',
        request_serializer=grpc__img__pb2.ImageRequest.SerializeToString,
        response_deserializer=grpc__img__pb2.ImageReply.FromString,
        )


class testImageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_testImageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendImage': grpc.unary_unary_rpc_method_handler(
          servicer.SendImage,
          request_deserializer=grpc__img__pb2.ImageRequest.FromString,
          response_serializer=grpc__img__pb2.ImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'testImage', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
